### ISSUE TITLE
Filter broken

### ISSUE THREAD

**Issue by maxapasov** [batstyx/Hearthstone-Collection-Tracker#4]
Roll up some addons but "Manage Standart Cards" show all cards.
In older version it show cards only from selected addons.

**Comment by batstyx** [comment]
I don't think it's broken so much as removed. This must have been a while ago as there's nothing in the last few years code history that indicates to me the behaviour you describe. I'm only guessing, but I suspect 'filter by visible set' was replaced by the 'Manage All'/Manage Standard'/'Manage Set' buttons for performance reasons as the number of sets increased. 
I'll leave this open but it's probably not something I'm going to seriously look at anytime soon.

**Comment by batstyx** [comment]
https://github.com/batstyx/Hearthstone-Collection-Tracker/releases/tag/v0.11
